name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      # Создаём firebase-config.js из секрета
      - name: Create firebase-config.js from secret
        run: echo "$FIREBASE_CONFIG_JS" > firebase-config.js
        env:
          FIREBASE_CONFIG_JS: ${{ secrets.FIREBASE_CONFIG_JS }}

      # Явно копируем firebase-config.js в publish_dir (./)
      - name: Ensure firebase-config.js is in publish_dir
        run: cp firebase-config.js ./

      # (Если нужен build — добавьте шаги сборки)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ 